main: network.synity.ModReq.Main
name: ModReq
version: 1.0
author: Liam / Puggetty
description: Sends a private request to moderators.
commands:
  modreq:
    description: Requests help from a moderator.
